[workspace]
members = [
    "crates/models",
    "crates/db",
    "crates/parser",
    "crates/api",
    "crates/platforms",
    "crates/config",
    "crates/watcher",
    "crates/launcher",
    "crates/images",
    "crates/ira",
]
resolver = "2"

[workspace.lints.clippy]
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
