[workspace]
members = [
    "crates/models",
    "crates/db",
    "crates/parser",
    "crates/api",
    "crates/platforms",
    "crates/config",
    "crates/watcher",
    "crates/launcher",
    "crates/images",
    "crates/ira",
    "crates/overlay",
    "crates/overlay-ipc",
    "crates/overlay-shim",
    "crates/overlay-vk",
    "crates/overlay-standalone",
]
resolver = "2"

[workspace.lints.clippy]
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
