pub mod state;
mod css;
mod game_item;
mod grid_bin;
mod window;
mod sidebar;
mod grid_view;
mod game_display;
mod achievement_rows;
mod image_budget;
mod play_button;
mod message_handler;
mod helpers;
mod enrichment;
mod background;
mod dialogs;
mod context_menu;
mod mass_match_dialog;
mod add_game;
mod add_game_dialog;
mod edit_game_dialog;
mod play_history;
mod wine_config_widget;
mod profile_dialog;
mod matching;
mod filter;
mod group_dialog;

pub use state::{AppState, SharedState, malloc_trim};
pub use window::build_ui;
pub use message_handler::{handle_app_message, switch_to_game};
pub use background::{hide_to_background, restore_content};
pub use enrichment::enrich_game_async;
pub use game_item::GameItem;
pub use grid_bin::GridBin;
