mod state;
mod css;
mod game_item;
mod grid_bin;
mod game_selection_model;
mod sidebar_item;
mod window;
mod sidebar;
mod grid_view;
mod achievement_view;
mod game_display;
mod game_header;
mod achievement_rows;
mod image_budget;
mod play_button;
mod message_handler;
mod helpers;
mod enrichment;
mod background;
mod context_menu;
mod mass_match_dialog;
mod steam_search_dialog;
mod sgdb_match_dialog;
mod ra_match_dialog;
pub use ra_match_dialog::show_ra_search_dialog;
mod settings_pages;
mod settings_console;
mod settings_dialog;
mod game_settings;
mod steam_search;
mod game_logo;
mod image_manager;
mod sgdb_picker;
pub use settings_dialog::show_settings_dialog;
pub use image_manager::{build_image_manager_content, build_image_manager_content_with_drafts};
mod add_game;
mod add_game_dialog;
mod add_game_general;
mod add_game_env;
mod add_game_db;
mod edit_game_dialog;
mod edit_game_launch;
mod edit_game_pages;
mod play_history;
mod wine_config_helpers;
mod wine_config_env_dll;
mod wine_config_widget;
mod profile_dialog;
mod matching;
mod filter;
mod group_dialog;

pub use state::{AppState, SharedState, malloc_trim};
pub use window::{build_ui, AppContext};
pub use message_handler::{handle_app_message, switch_to_game};
pub use background::{hide_to_background, restore_content};
pub use enrichment::enrich_game_async;
pub use game_item::GameItem;
pub use grid_bin::GridBin;
