pub fn native_names(console: &str) -> &'static [&'static str] {
    match console {
        "3do" => &["opera"],
        "amiga" | "cdtv" => &["fs-uae", "amiberry"],
        "amstradcpc" => &["caprice32", "cpcemu", "mame"],
        "apple2" => &["linapple", "izapple2", "mame"],
        "arcade" => &[
            "mame",
            "mame64",
            "hbmame",
            "finalburnneo",
            "flycast",
            "kronos",
            "supermodel",
        ],
        "atari2600" => &["stella"],
        "atari5200" | "atari800" => &["atari800"],
        "atari7800" => &["prosystem", "mame"],
        "atarijaguar" | "atarijaguarcd" => &["virtualjaguar", "mame"],
        "atarilynx" => &["mednafen"],
        "atarist" => &["hatari"],
        "c64" => &["x64sc", "vice"],
        "cdimono1" | "channelf" | "gameandwatch" | "gamecom" => &["mame"],
        "coco" => &["xroar", "mame"],
        "colecovision" | "msx" | "msx1" | "msx2" => &["openmsx", "mame"],
        "intellivision" => &["jzintv", "mame"],
        "megaduck" => &["mame"],
        "neogeocd" | "neogeocdjp" => &["mame", "finalburnneo"],
        "odyssey2" | "videopac" => &["o2em", "mame"],
        "pc88" => &["quasi88"],
        "pc98" => &["np2"],
        "pcfx" => &["mednafen"],
        "pokemini" => &["pokemini"],
        "psvita" => &["vita3k"],
        "sega32x" => &["picodrive", "ares"],
        "segacd" => &["kega-fusion", "ares"],
        "sg-1000" => &["mednafen"],
        "sgb" => &["mgba", "mesen"],
        "sufami" => &["snes9x", "bsnes", "mesen"],
        "supergrafx" => &["mednafen", "mesen", "geargrafx"],
        "supervision" | "vsmile" => &["mame"],
        "vectrex" => &["vecx", "mame"],
        "vircon32" => &["vircon32"],
        "wiiu" => &["cemu"],
        "x68000" => &["px68k", "mame"],
        "xbox" => &["xemu"],
        "zxnext" => &["cspect", "zesarux"],
        "zx81" => &["81"],
        "zxspectrum" => &["fuse", "zesarux"],
        "psx" => &["mednafen", "pcsx-rearmed", "ares"],
        "ps2" => &["pcsx2"],
        "psp" => &["ppsspp"],
        "nes" => &["mesen", "nestopia", "fceux", "mednafen", "punes", "ares"],
        "snes" => &["snes9x", "bsnes", "mednafen", "mesen", "ares"],
        "gb" | "gbc" => &["sameboy", "mgba", "mednafen", "gearboy"],
        "gba" => &["mgba", "mednafen", "visualboyadvance-m"],
        "n64" | "n64dd" => &["mupen64plus", "simple64", "parallel-launcher", "ares"],
        "nds" => &["melonds", "desmume", "noods", "skyemu"],
        "virtualboy" => &["mednafen", "ares"],
        "sat" => &["snes9x", "bsnes", "mesen"],
        "md" => &["blastem", "gens", "mednafen", "ares", "kega-fusion"],
        "sms" | "gg" => &["mednafen", "blastem", "mesen", "ares"],
        "saturn" => &["mednafen", "yabause", "kronos"],
        "dc" => &["flycast", "redream"],
        "neogeo" => &["mame", "mednafen", "finalburnneo"],
        "ngp" | "ngpc" => &["mednafen", "ares"],
        "pce" | "pcecd" => &["mednafen", "mesen", "geargrafx", "ares"],
        "ws" | "wsc" => &["mednafen", "mesen", "ares"],
        _ => &[],
    }
}

pub fn core_names(console: &str) -> &'static [&'static str] {
    match console {
        "3do" => &["opera"],
        "amiga" | "cdtv" => &["puae", "puae2021"],
        "amstradcpc" => &["cap32", "crocods"],
        "apple2" => &["applewin", "mame"],
        "arcade" => &[
            "mame",
            "mame2010",
            "mame2003_plus",
            "mame2003",
            "mame2000",
            "hbmame",
            "fbneo",
            "fbalpha2012",
            "geolith",
            "flycast",
            "kronos",
            "dice",
        ],
        "arduboy" => &["arduous", "ardens"],
        "atari2600" => &["stella", "stella2014", "stella2023", "tia"],
        "atari5200" => &["a5200", "atari800"],
        "atari7800" => &["prosystem", "mame"],
        "atari800" => &["atari800"],
        "atarijaguar" | "atarijaguarcd" => &["virtualjaguar", "mame"],
        "atarilynx" => &["handy", "mednafen_lynx", "gearlynx", "holani"],
        "atarist" => &["hatari"],
        "c64" => &["vice_x64sc", "vice_x64", "vice_xscpu64", "frodo"],
        "cdimono1" => &["same_cdi", "cdi2015", "mame"],
        "channelf" => &["freechaf", "mame"],
        "coco" => &["mame"],
        "colecovision" => &["bluemsx", "gearcoleco", "jollycv"],
        "gameandwatch" => &["gw", "mame"],
        "gamecom" => &["mame"],
        "intellivision" => &["freeintv", "jzintv", "mame"],
        "megaduck" => &["mame"],
        "msx" | "msx1" | "msx2" => &["bluemsx", "fmsx"],
        "neogeocd" | "neogeocdjp" => &["neocd", "fbneo"],
        "ngpc" => &["mednafen_ngp", "race"],
        "odyssey2" | "videopac" => &["o2em", "mame"],
        "pc88" => &["quasi88"],
        "pc98" => &["np2kai", "nekop2"],
        "pcfx" => &["mednafen_pcfx"],
        "pokemini" => &["pokemini"],
        "sega32x" => &["picodrive"],
        "segacd" => &[
            "genesis_plus_gx",
            "genesis_plus_gx_wide",
            "picodrive",
            "clownmdemu",
        ],
        "sg-1000" => &[
            "genesis_plus_gx",
            "genesis_plus_gx_wide",
            "gearsystem",
            "bluemsx",
        ],
        "sgb" => &["mesen_s", "sameboy", "mgba"],
        "sufami" => &["snes9x", "bsnes", "mesen_s"],
        "supergrafx" => &[
            "mednafen_supergrafx",
            "mednafen_pce",
            "mednafen_pce_fast",
            "geargrafx",
        ],
        "supervision" => &["potator", "mame"],
        "vectrex" => &["vecx", "mame"],
        "vircon32" => &["vircon32"],
        "vsmile" => &["mame"],
        "wiiu" | "xbox" | "switch" | "psvita" | "zxnext" | "zx81" => &[],
        "x68000" => &["px68k", "mame"],
        "zxspectrum" => &["fuse"],
        "gc" | "wii" => &["dolphin"],
        "psx" => &[
            "mednafen_psx",
            "mednafen_psx_hw",
            "pcsx_rearmed",
            "swanstation",
        ],
        "ps2" => &["pcsx2"],
        "psp" => &["ppsspp"],
        "nes" => &["mesen", "nestopia", "fceumm", "quicknes", "mesen", "fceumm"],
        "snes" => &[
            "snes9x",
            "snes9x2010",
            "snes9x2005_plus",
            "bsnes",
            "bsnes_hd_beta",
            "mesen_s",
            "mednafen_supafaust",
        ],
        "gb" => &[
            "gambatte",
            "sameboy",
            "mgba",
            "gearboy",
            "tgbdual",
            "mednafen_gb",
        ],
        "gbc" => &[
            "gambatte",
            "sameboy",
            "mgba",
            "gearboy",
            "tgbdual",
            "mednafen_gbc",
        ],
        "gba" => &["mgba", "vba_next", "vba-m", "gpsp", "mednafen_gba"],
        "n64" | "n64dd" => &["mupen64plus_next", "parallel_n64"],
        "nds" => &[
            "melondsds",
            "melonds",
            "desmume",
            "desmume2015",
            "noods",
            "skyemu",
        ],
        "virtualboy" => &["mednafen_vb"],
        "sat" => &["snes9x", "snes9x2010", "bsnes", "mesen_s"],
        "md" => &[
            "genesis_plus_gx",
            "genesis_plus_gx_wide",
            "picodrive",
            "blastem",
        ],
        "sms" | "gg" => &[
            "genesis_plus_gx",
            "genesis_plus_gx_wide",
            "gearsystem",
            "smsplus",
        ],
        "saturn" => &["mednafen_saturn", "kronos", "yabasanshiro", "yabause"],
        "dc" => &["flycast"],
        "neogeo" => &["fbneo", "geolith", "mame"],
        "ngp" => &["mednafen_ngp", "race"],
        "pce" | "pcecd" => &[
            "mednafen_pce",
            "mednafen_pce_fast",
            "mednafen_supergrafx",
            "geargrafx",
        ],
        "ws" | "wsc" => &["mednafen_wswan"],
        _ => &[],
    }
}

pub fn has_retroarch_cores(console: &str) -> bool {
    !matches!(
        console,
        "ps3" | "ps4" | "psvita" | "switch" | "wiiu" | "xbox" | "zx81" | "zxnext"
    )
}
